# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Quantile function for exponential
#' 
#' Compute the quantile given a probability
#' 
#' @param p      Vector of Probabilities.
#' @param lambda Double of lambda.
#' 
#' @return 
#' A vector of quantiles
#' 
#' @examples
#' # Compute one quantile
#' qexp_arma(0.6, 2)
#' 
#' # Compute two quantiles
#' qexp_arma(c(0.5, 0.2), 3)
qexp_arma <- function(p, lambda = 2) {
    .Call(`_r11_qexp_arma`, p, lambda)
}

#' Simulate samples from an Exponential Distribution
#' 
#' Generates random values from an exponential distribution.
#' 
#' @param n      Number of observations to generate
#' @param lambda Rate parameter
#' @param seed   Starting value for the Random Number Generator (RNG).
#' 
#' @return A vector of random numbers from an exponential distribution.
#' @examples
#' # Generate a random number
#' rexp_arma(1, lambda = 2)
#' 
#' # Generate two random numbers
#' rexp_arma(2, lambda = 9, seed = 8235)
rexp_arma <- function(n, lambda = 2, seed = 183L) {
    .Call(`_r11_rexp_arma`, n, lambda, seed)
}

