# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulate samples from a Uniform Distribution
#' 
#' Generates random values from the C++11 Uniform Distribution.
#' 
#' @param n      Number of observations to generate
#' @param start  Beginning range of values
#' @param end    End range of values
#' @param seed   Starting value for the Random Number Generator (RNG).
#' 
#' @return 
#' A vector of random numbers from the Uniform distribution.
#' 
#' @export
#' @examples
#' # Generate a random number
#' runif_arma(1, start = 2, end = 20)
#' 
#' # Generate two random numbers
#' runif_arma(2, start = 5, end = 30)
runif_arma <- function(n, start = 0.0, end = 1.0, seed = 183L) {
    .Call(`_r11_runif_arma`, n, start, end, seed)
}

