# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

qexp <- function(u, lambda) {
    .Call('_r11_qexp', PACKAGE = 'r11', u, lambda)
}

rexp <- function(n, lambda, seed) {
    .Call('_r11_rexp', PACKAGE = 'r11', n, lambda, seed)
}

